repos:
  - hooks:
      - id: black
        language_version: python3
    repo: https://github.com/ambv/black
    rev: 22.10.0
  - hooks:
      - id: isort
        language_version: python3
    repo: https://github.com/PyCQA/isort
    rev: 5.12.0
  - hooks:
    - id: mypy
      additional_dependencies: [types-requests, types-mock, types-six, lxml-stubs]
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
